'use client';

// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import './styles/klinechart.css';
import Navibar from './components/shared/Navibar/Navibar';
import { ThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class'>
          <Navibar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
