// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import './styles/klinechart.css';
import './styles/marketDepth.css';
import type { Metadata } from 'next';
import Navibar from './components/shared/Navibar/Navibar';
import AppProvider from './components/shared/AppProvider/AppProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'dex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`dark:bg-black-gradient bg-offWhite ${inter.className}`}>
        <AppProvider>
          <Navibar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
